=== Otvos-Adam-Balazs/BKDZXB_XMLGyak/BKDZXB_1006/BKDZXB_mozi1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/BKDZXB_mozi1" xmlns:tns="http://www.example.org/BKDZXB_mozi1" elementFormDefault="qualified">
	<element name="mozi">
		<complexType>
			<sequence>
				<element name="film" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="rendezo" maxOccurs="unbounded">
								<complexType>
									<attribute name="id" type="string" use="required"/>
									<attribute name="nev" type="string" use="required"/>
								</complexType>
							</element>	
							<element name="szinesz">
									<complexType>
									<attribute name="id" type="string" use="required"/>
									<attribute name="nev" type="string" use="required"/>
								</complexType>
							</element>
							<element name="iro">
									<complexType>
									<attribute name="id" type="string" use="required"/>
								</complexType>
							</element>
						</sequence>
						<attribute name="id" type="string" use="required"/>
						<attribute name="mufaj" type="string" use="required"/>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>


</schema>

=== Otvos-Adam-Balazs/BKDZXB_XMLGyak/BKDZXB_1006/mozi1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- !DOCTYPE mozi SYSTEM "BKDZXB_mozi1.dtd"> -->

<mozi xmlns:xsi="https://w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="BKDZXB_mozi1.xsd">

	<film id="m1" mufaj="horror">
	 <rendezo id="m1" nev="alex"/>
	 <rendezo id="m2" nev="alex"/>
	 <szinesz id="m1" nev="Madison Ivy"/>
	 <iro id="m1"/>
	</film>
	
	<film id="m2" mufaj="scifi">
	 <rendezo id="m3" nev="alex"/>
	 <rendezo id="m4" nev="alex"/>
	 <szinesz id="m2" nev="Madison Ivy"/>
	 <iro id="m2" />
	</film>
</mozi>
